name: 'user-web'
port: 8021

user_srv:
  host: '127.0.0.1'
  port: 50051

jwt:
  key: '5$!UEmvB#nRB@Iwab#Sy!zofKEOGLRtE'

sms:
  key: 'LTAI4FzGkwzJyrKfCex9kpP1'
  secret: 'r5aWSxybxkuT4ROcwpRqqisXtcwxt5'
  expire: 300

redis:
  host: '127.0.0.1'
  port: 6379

consul:
  host: '127.0.0.1'
  port: 8500